name: paynote_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.1+3

environment:
  sdk: ">=2.7.0 <3.0.0"



dependencies:
  flutter:
    sdk: flutter
  flutter_uxcam: ^1.1.1
  intro_slider: ^2.3.3

  image_picker: ^0.6.1+4
  international_phone_input: ^1.0.4
  pinput:
  intl_phone_number_input:

  pin_code_fields: ^5.2.0
  flutter_switch: ^0.1.2
  percent_indicator: "^2.1.7+2"
  flutter_svg: ^0.18.0
  intl: ^0.16.1

  #imports for profile
  csv: ^5.0.0


  pin_code_text_field: ^1.7.1
  datetime_picker_formfield: ^1.0.0
  select_form_field: ^1.0.1
  #localization
  easy_localization: any
  # state manegement
  stacked: any
  stacked_services: any
  auto_route: any
  get_it: any
  injectable: any
  observable_ish:
  retrofit: any
  logger: any
  dio: any
  json_annotation: any
  path_provider:
    # Hive
  hive:
  hive_flutter:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  page_transition: ^1.1.7+2
  shared_preferences:
  flutter_launcher_icons:
  firebase_dynamic_links:
  flutter_inappwebview:
  charts_flutter:
  syncfusion_flutter_charts:
  flutter_screenutil: ^4.0.3+1
  relative_scale: ^1.1.0
  #for loading screens
  overlay_screen: ^1.2.0+1
  #for preventing screenshots
  flutter_windowmanager:
  url_launcher:
  twilio_phone_verify:

  #for infinite pagination
  infinite_scroll_pagination:
  http:
  cached_network_image:
  firebase_messaging: ^9.1.2
  flutter_local_notifications: ^5.0.0+1
  firebase_core:
  obscured_preferences: ^0.1.0

flutter_icons:
  android: true
  ios: true
  image_path: "Assets/Logo/PNG/#2 _blue.png"
  #adaptive_icon_background: "assets/app/background.png"
  #adaptive_icon_foreground: "assets/app/foreground.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  retrofit_generator: any
  auto_route_generator: null
  injectable_generator: any
  json_serializable: any
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - Assets/translations/TranslationTagsFinal.csv
    - Assets/translations/
    - Assets/Logo/PNG/#1 _blue.png
    - Assets/Illustrations/Tech_1.png
    - Assets/Illustrations/Tech_2.png
    - Assets/Illustrations/Tech_3.png
    - Assets/Illustrations/Tech_4.png
    - Assets/Illustrations/Tech_5.png
    - Assets/Illustrations/Tech_loading.png
    - Assets/Logo_Placeholder.jpg
    - Assets/Illustrations/default.jpg

  fonts:
    - family: Alata
      fonts:
        - asset: fonts/Alata-Regular.ttf

    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Black.ttf
        - asset: fonts/Roboto/Roboto-BlackItalic.ttf
        - asset: fonts/Roboto/Roboto-Bold.ttf
        - asset: fonts/Roboto/Roboto-BoldItalic.ttf
        - asset: fonts/Roboto/Roboto-Italic.ttf
        - asset: fonts/Roboto/Roboto-Light.ttf
        - asset: fonts/Roboto/Roboto-LightItalic.ttf
        - asset: fonts/Roboto/Roboto-Medium.ttf
        - asset: fonts/Roboto/Roboto-MediumItalic.ttf
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Thin.ttf
        - asset: fonts/Roboto/Roboto-ThinItalic.ttf

    - family:  PaynoteIcons
      fonts:
       - asset: fonts/Icons/PaynoteIcons.ttf

  uses-material-design: true

